metadata:
  name: lnmp-mysql
  selfLink: /api/v1/persistentvolumes/lnmp-mysql
  uid: 8674a68f-70dd-469e-a527-fe3497a8b152
  resourceVersion: '182156'
  creationTimestamp: '2019-08-05T06:49:57Z'
  labels:
    lnmp: mysql
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.102
    path: /nfs/data/lnmp/mysql
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: lnmp
    name: lnmp-mysql
    uid: a24d3221-6f84-4eb3-b5c7-d8109f8b541c
    apiVersion: v1
    resourceVersion: '182044'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
status:
  phase: Bound


 ---

 kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lnmp-mysql
  namespace: lnmp
  selfLink: /api/v1/namespaces/lnmp/persistentvolumeclaims/lnmp-mysql
  uid: a24d3221-6f84-4eb3-b5c7-d8109f8b541c
  resourceVersion: '182158'
  creationTimestamp: '2019-08-05T06:49:00Z'
  labels:
    app: lnmp-mysql
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      lnmp: mysql
  resources:
    requests:
      storage: 1Gi
  volumeName: lnmp-mysql
  storageClassName: nfs
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  ---

  kind: Service
apiVersion: v1
metadata:
  name: lnmp-mysql
  namespace: lnmp
  selfLink: /api/v1/namespaces/lnmp/services/lnmp-mysql
  uid: 4024f6e3-d59b-45c9-a24d-6bf7c6985abd
  resourceVersion: '255067'
  creationTimestamp: '2019-08-07T10:20:53Z'
  labels:
    app: lnmp-mysql
    wayne-app: lnmp
    wayne-ns: lnmp
spec:
  ports:
    - name: lnmp-mysql-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: 10.106.20.215
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

 ---
 kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: lnmp-mysql
  namespace: lnmp
  selfLink: /apis/apps/v1beta1/namespaces/lnmp/deployments/lnmp-mysql
  uid: 2b514439-16b0-4de4-bc28-c3769788cd73
  resourceVersion: '254946'
  generation: 1
  creationTimestamp: '2019-08-07T10:19:35Z'
  labels:
    app: mysql
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
      annotations:
        wayne.cloud/controller-kind: deployment
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lnmp-mysql
      containers:
        - name: mysql
          image: 'mysql:5.6'
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yjcadmin
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-08-07T10:19:35Z'
      lastTransitionTime: '2019-08-07T10:19:35Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-08-07T10:19:38Z'
      lastTransitionTime: '2019-08-07T10:19:35Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "lnmp-mysql-797947fc5" has successfully progressed.



