kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: lnmp-nginx
  namespace: lnmp
  selfLink: /apis/apps/v1beta1/namespaces/lnmp/deployments/lnmp-nginx
  uid: 18fd48e8-cc24-46be-a619-eda58e136c17
  resourceVersion: '255847'
  generation: 2
  creationTimestamp: '2019-08-07T10:19:12Z'
  labels:
    app: nginx
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
      annotations:
        wayne.cloud/controller-kind: deployment
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lnmp-phpnginx
        - name: project
          persistentVolumeClaim:
            claimName: lnmp-phpproject
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx
            - name: project
              mountPath: /var/www/html
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-08-07T10:19:20Z'
      lastTransitionTime: '2019-08-07T10:19:12Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "lnmp-nginx-8595c8f559" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-08-07T10:30:46Z'
      lastTransitionTime: '2019-08-07T10:30:46Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    ---

    kind: Service
apiVersion: v1
metadata:
  name: lnmp-nginx
  namespace: lnmp
  selfLink: /api/v1/namespaces/lnmp/services/lnmp-nginx
  uid: a2d2103d-531f-4647-abfb-1cc9059a1aa9
  resourceVersion: '255057'
  creationTimestamp: '2019-08-07T10:20:48Z'
  labels:
    app: lnmp-nginx
    wayne-app: lnmp
    wayne-ns: lnmp
spec:
  ports:
    - name: lnmp-nginx-80
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32110
  selector:
    app: nginx
  clusterIP: 10.105.186.131
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
    ---

    metadata:
  name: phpnginx
  selfLink: /api/v1/persistentvolumes/phpnginx
  uid: 7e19c023-6c10-4fbe-a41e-2f23ed1e5398
  resourceVersion: '168706'
  creationTimestamp: '2019-08-04T13:30:02Z'
  labels:
    lnmp: phpnginx
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.102
    path: /nfs/data/lnmp/lnmp-project/nginxconf
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: lnmp
    name: lnmp-phpnginx
    uid: 00e71419-03a0-48c6-9c36-bab7c8a8a084
    apiVersion: v1
    resourceVersion: '168704'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
status:
  phase: Bound
    ---
    kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lnmp-phpnginx
  namespace: lnmp
  selfLink: /api/v1/namespaces/lnmp/persistentvolumeclaims/lnmp-phpnginx
  uid: 00e71419-03a0-48c6-9c36-bab7c8a8a084
  resourceVersion: '168708'
  creationTimestamp: '2019-08-04T13:30:49Z'
  labels:
    app: lnmp-phpnginx
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      lnmp: phpnginx
  resources:
    requests:
      storage: 1Gi
  volumeName: phpnginx
  storageClassName: nfs
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi

